@baseUrl=http://localhost:8080/api/posts

### foldername
GET {{baseUrl}}/foldername

### posts list (/api/posts)
GET {{baseUrl}}

### create post
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "제목...",
  "writer": "홍길동",
  "contents": "내용..."
}

### edit post
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "title": "제목22...",
  "contents": "내용..."
}

### post detail
GET {{baseUrl}}/100
